root_dataset_path: /data/training_datasets/detection
annotation_files_dir: /data/training_datasets/detection/annotations
unlabeled_dataset_path: /data/training_datasets/detection/unlabeled_data
train_file: subset_train_2_det_coco_2023-04-19.json
val_file: val_2_det_coco_2023-04-19.json

TRAIN_SIZE: 8
VAL_SIZE: 8
UNLABELED_SIZE: 8

IOU_TH: 0.3
BACKGROUND_LABEL: 4
CLASSES: 3
CONF_THRESH: 0.5
TOP_K: 100
IMAGE_SIZE: [640, 640]
LOAD_UNION_CATEGORIES_IMAGES: true
MAX_BB_PER_IMAGE: 20
MODEL_FORMAT: inference
NMS_THRESH: 0.6
OFFSET: 0
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
FEATURE_MAPS:
- - 80
  - 80
- - 40
  - 40
- - 20
  - 20
