root_dataset_path: /Users/ranhomri/tensorleap/data/metropolis-data-mock/images
annotation_files_dir: /Users/ranhomri/tensorleap/data/metropolis-data-mock/annotations/2023-04-19
unlabeled_dataset_path: /Users/ranhomri/tensorleap/data/metropolis-data-mock/unlabeled_data
train_file: subset_train_2_det_coco_2023-04-19.json
val_file: val_2_det_coco_2023-04-19.json

TRAIN_SIZE: 8
VAL_SIZE: 8
UNLABELED_SIZE: 8

gt_xy_center: False
predict_log_wh: True

CLASSES: 80
POSE_CLS: 3
TYPE_CLS: 8

GT_CLS_IDX: 4
GT_POSE_IDX: 5
GT_TYPE_IDX: 6

IOU_TH: 0.3
CONF_THRESH: 0.5
TOP_K: 10
IMAGE_SIZE: [640, 640]
LOAD_UNION_CATEGORIES_IMAGES: true
MAX_BB_PER_IMAGE: 20
MODEL_FORMAT: inference
NMS_THRESH: 0.6
OFFSET: 0
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
FEATURE_MAPS:
- - 80
  - 80
- - 40
  - 40
- - 20
  - 20
