root_dataset_path: /Users/ranhomri/tensorleap/data/metropolis-data-mock/images
annotation_files_dir: /Users/ranhomri/tensorleap/data/metropolis-data-mock/annotations
unlabeled_dataset_path: /Users/ranhomri/tensorleap/data/metropolis-data-mock/unlabeled/
train_file: train.json
val_file: val.json

TRAIN_SIZE: 8
VAL_SIZE: 8
UNLABELED_SIZE: 8

IOU_TH: 0.3
BACKGROUND_LABEL: 81
CLASSES: 80
CONF_THRESH: 0.35
TOP_K: 100
IMAGE_SIZE: [640, 640]
LOAD_UNION_CATEGORIES_IMAGES: true
MAX_BB_PER_IMAGE: 20
MODEL_FORMAT: inference
NMS_THRESH: 0.6
OFFSET: 0
OVERLAP_THRESH: 0.0625
SMALL_BBS_TH: 0.0003
STRIDES:
- 8
- 16
- 32
FEATURE_MAPS:
- - 80
  - 80
- - 40
  - 40
- - 20
  - 20
